using crm_api.Shared.Common.Application.Common;

namespace crm_api.Modules.Definitions.Localization;

public sealed class DefinitionsLocalizationResource : ILocalizationResource
{
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> MessagesByCulture { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "An error occurred while creating the Document Serial Type: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "An error occurred while deleting the Document Serial Type: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "Document Serial Type not found.",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "Document Serial Types retrieved successfully.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "An error occurred: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "An error occurred while retrieving Document Serial Types: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "An error occurred during the operation: {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "An error occurred while retrieving the Document Serial Type: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "Internal server error occurred.",
                ["DocumentSerialTypeService.TypeCreated"] = "Document Serial Type created successfully.",
                ["DocumentSerialTypeService.TypeDeleted"] = "Document Serial Type deleted successfully.",
                ["DocumentSerialTypeService.TypeNotFound"] = "Document Serial Type not found.",
                ["DocumentSerialTypeService.TypeRetrieved"] = "Document Serial Type retrieved successfully.",
                ["DocumentSerialTypeService.TypeUpdated"] = "Document Serial Type updated successfully.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "Document Serial Types retrieved successfully.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "An error occurred while updating the Document Serial Type: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "Name is required.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "Name must be 150 characters or fewer.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "Sales type is invalid. Allowed values: YURTICI, YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "Sales type is required.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "Sales type must be 20 characters or fewer.",
                ["SalesTypeService.SalesTypeAlreadyExists"] = "Sales type already exists.",
                ["SalesTypeService.SalesTypeCreated"] = "Sales type created successfully.",
                ["SalesTypeService.SalesTypeDeleted"] = "Sales type deleted successfully.",
                ["SalesTypeService.SalesTypeInvalid"] = "Sales type is invalid.",
                ["SalesTypeService.SalesTypeNotFound"] = "Sales type not found.",
                ["SalesTypeService.SalesTypeRetrieved"] = "Sales type retrieved successfully.",
                ["SalesTypeService.SalesTypeUpdated"] = "Sales type updated successfully.",
                ["SalesTypeService.SalesTypesRetrieved"] = "Sales types retrieved successfully.",
            },
            ["tr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "Document Serial Type olu\u015fturulurken bir hata olu\u015ftu: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "Document Serial Type silinirken bir hata olu\u015ftu: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "Document Serial Type bulunamad\u0131.",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "Document Serial Typeler ba\u015far\u0131yla getirildi.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "Bir hata olu\u015ftu: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "Document Serial Typeler getirilirken bir hata olu\u015ftu: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "Kullan\u0131labilir belge seri tipleri al\u0131n\u0131rken bir hata olu\u015ftu: {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "Document Serial Type getirilirken bir hata olu\u015ftu: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "Sunucu hatas\u0131 olu\u015ftu.",
                ["DocumentSerialTypeService.TypeCreated"] = "Document Serial Type ba\u015far\u0131yla olu\u015fturuldu.",
                ["DocumentSerialTypeService.TypeDeleted"] = "Document Serial Type ba\u015far\u0131yla silindi.",
                ["DocumentSerialTypeService.TypeNotFound"] = "Document Serial Type bulunamad\u0131.",
                ["DocumentSerialTypeService.TypeRetrieved"] = "Document Serial Type ba\u015far\u0131yla getirildi.",
                ["DocumentSerialTypeService.TypeUpdated"] = "Document Serial Type ba\u015far\u0131yla g\u00fcncellendi.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "Document Serial Typeler ba\u015far\u0131yla getirildi.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "Document Serial Type g\u00fcncellenirken bir hata olu\u015ftu: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "Ad alan\u0131 zorunludur.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "Ad alan\u0131 en fazla 150 karakter olabilir.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "Sat\u0131\u015f tipi ge\u00e7ersiz. Ge\u00e7erli de\u011ferler: YURTICI, YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "Sat\u0131\u015f tipi zorunludur.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "Sat\u0131\u015f tipi en fazla 20 karakter olabilir.",
            },
            ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "Fehler beim Erstellen von the Dokument Serie Typ: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "Fehler beim L\u00f6schen von the Dokument Serie Typ: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "Dokumentserientyp nicht gefunden.",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "Dokument Serie Types erfolgreich abgerufen.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "An error occurred: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "Fehler beim Abrufen von Dokument Serie Types: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "Beim Vorgang ist ein Fehler aufgetreten: {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "Fehler beim Abrufen von the Dokument Serie Typ: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "Interner Serverfehler aufgetreten.",
                ["DocumentSerialTypeService.TypeCreated"] = "Dokumentserientyp erfolgreich erstellt.",
                ["DocumentSerialTypeService.TypeDeleted"] = "Dokumentserientyp erfolgreich gel\u00f6scht.",
                ["DocumentSerialTypeService.TypeNotFound"] = "Dokumentserientyp nicht gefunden.",
                ["DocumentSerialTypeService.TypeRetrieved"] = "Dokumentserientyp erfolgreich abgerufen.",
                ["DocumentSerialTypeService.TypeUpdated"] = "Dokumentserientyp erfolgreich aktualisiert.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "Dokument Serie Types erfolgreich abgerufen.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "Fehler beim Aktualisieren von the Dokument Serie Typ: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "Der Name ist erforderlich.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "Der Name darf h\u00f6chstens 150 Zeichen lang sein.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "Der Verkaufstyp ist ung\u00fcltig. Zul\u00e4ssige Werte: YURTICI, YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "Der Verkaufstyp ist erforderlich.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "Der Verkaufstyp darf h\u00f6chstens 20 Zeichen lang sein.",
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "Une erreur est survenue lors de la cr\u00e9ation de the Document S\u00e9rie Type: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "Une erreur est survenue lors de la suppression de the Document S\u00e9rie Type: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "Type de s\u00e9rie de document non trouv\u00e9(e).",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "Document S\u00e9rie Types r\u00e9cup\u00e9r\u00e9(e) avec succ\u00e8s.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "An error occurred: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "Une erreur est survenue lors de la r\u00e9cup\u00e9ration de Document S\u00e9rie Types: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "Une erreur s'est produite pendant l'op\u00e9ration : {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "Une erreur est survenue lors de la r\u00e9cup\u00e9ration de the Document S\u00e9rie Type: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "Une erreur interne du serveur s'est produite.",
                ["DocumentSerialTypeService.TypeCreated"] = "Type de s\u00e9rie de document cr\u00e9\u00e9(e) avec succ\u00e8s.",
                ["DocumentSerialTypeService.TypeDeleted"] = "Type de s\u00e9rie de document supprim\u00e9(e) avec succ\u00e8s.",
                ["DocumentSerialTypeService.TypeNotFound"] = "Type de s\u00e9rie de document non trouv\u00e9(e).",
                ["DocumentSerialTypeService.TypeRetrieved"] = "Type de s\u00e9rie de document r\u00e9cup\u00e9r\u00e9(e) avec succ\u00e8s.",
                ["DocumentSerialTypeService.TypeUpdated"] = "Type de s\u00e9rie de document mis(e) \u00e0 jour avec succ\u00e8s.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "Document S\u00e9rie Types r\u00e9cup\u00e9r\u00e9(e) avec succ\u00e8s.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "Une erreur est survenue lors de la mise \u00e0 jour de the Document S\u00e9rie Type: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "Le nom est requis.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "Le nom doit contenir au maximum 150 caract\u00e8res.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "Le type de vente est invalide. Valeurs autoris\u00e9es : YURTICI, YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "Le type de vente est requis.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "Le type de vente doit contenir au maximum 20 caract\u00e8res.",
            },
            ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "Ocurri\u00f3 un error al crear the Documento Serie Tipo: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "Ocurri\u00f3 un error al eliminar the Documento Serie Tipo: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "Tipo de serie de documento no encontrado.",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "Documento Serie Types recuperado con \u00e9xito.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "An error occurred: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "Ocurri\u00f3 un error al recuperar Documento Serie Types: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "Se produjo un error durante la operaci\u00f3n: {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "Ocurri\u00f3 un error al recuperar the Documento Serie Tipo: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "Ocurri\u00f3 un error interno del server.",
                ["DocumentSerialTypeService.TypeCreated"] = "Tipo de serie de documento creado con \u00e9xito.",
                ["DocumentSerialTypeService.TypeDeleted"] = "Tipo de serie de documento eliminado con \u00e9xito.",
                ["DocumentSerialTypeService.TypeNotFound"] = "Tipo de serie de documento no encontrado.",
                ["DocumentSerialTypeService.TypeRetrieved"] = "Tipo de serie de documento recuperado con \u00e9xito.",
                ["DocumentSerialTypeService.TypeUpdated"] = "Tipo de serie de documento actualizado con \u00e9xito.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "Documento Serie Types recuperado con \u00e9xito.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "Ocurri\u00f3 un error al actualizar the Documento Serie Tipo: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "El nombre es obligatorio.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "El nombre debe tener 150 caracteres o menos.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "El tipo de venta no es v\u00e1lido. Valores permitidos: YURTICI, YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "El tipo de venta es obligatorio.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "El tipo de venta debe tener 20 caracteres o menos.",
            },
            ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "Si \u00e8 verificato un errore durante la creazione di the Documento Serie Tipo: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "Si \u00e8 verificato un errore durante l'eliminazione di the Documento Serie Tipo: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "Tipo di serie documento non trovato/a.",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "Documento Serie Types recuperato/a con successo.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "An error occurred: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "Si \u00e8 verificato un errore durante il recupero di Documento Serie Types: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "Si \u00e8 verificato un errore durante l'operazione: {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "Si \u00e8 verificato un errore durante il recupero di the Documento Serie Tipo: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "Si \u00e8 verificato un errore interno del server.",
                ["DocumentSerialTypeService.TypeCreated"] = "Tipo di serie documento creato/a con successo.",
                ["DocumentSerialTypeService.TypeDeleted"] = "Tipo di serie documento eliminato/a con successo.",
                ["DocumentSerialTypeService.TypeNotFound"] = "Tipo di serie documento non trovato/a.",
                ["DocumentSerialTypeService.TypeRetrieved"] = "Tipo di serie documento recuperato/a con successo.",
                ["DocumentSerialTypeService.TypeUpdated"] = "Tipo di serie documento aggiornato/a con successo.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "Documento Serie Types recuperato/a con successo.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "Si \u00e8 verificato un errore durante l'aggiornamento di the Documento Serie Tipo: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "Il nome \u00e8 obbligatorio.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "Il nome deve contenere al massimo 150 caratteri.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "Il tipo di vendita non \u00e8 valido. Valori consentiti: YURTICI, YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "Il tipo di vendita \u00e8 obbligatorio.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "Il tipo di vendita deve contenere al massimo 20 caratteri.",
            },
            ["ar"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["DocumentSerialTypeService.CreateTypeExceptionMessage"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u0623\u062b\u0646\u0627\u0621 \u0625\u0646\u0634\u0627\u0621 the \u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 \u0646\u0648\u0639: {0}",
                ["DocumentSerialTypeService.DeleteTypeExceptionMessage"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u0623\u062b\u0646\u0627\u0621 \u062d\u0630\u0641 the \u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 \u0646\u0648\u0639: {0}",
                ["DocumentSerialTypeService.DocumentSerialGenerated"] = "Document Serial Generated.",
                ["DocumentSerialTypeService.DocumentSerialTypeNotFound"] = "\u0646\u0648\u0639 \u062a\u0633\u0644\u0633\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f.",
                ["DocumentSerialTypeService.DocumentSerialTypesRetrieved"] = "\u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 Types \u062a\u0645 \u0627\u0633\u062a\u0631\u062c\u0627\u0639\u0647 \u0628\u0646\u062c\u0627\u062d.",
                ["DocumentSerialTypeService.GenerateDocumentSerialExceptionMessage"] = "An error occurred: {0}",
                ["DocumentSerialTypeService.GetAllTypesExceptionMessage"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u0623\u062b\u0646\u0627\u0621 \u0627\u0633\u062a\u0631\u062c\u0627\u0639 \u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 Types: {0}",
                ["DocumentSerialTypeService.GetAvaibleDocumentSerialTypesExceptionMessage"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u0623\u062b\u0646\u0627\u0621 \u0627\u0644\u0639\u0645\u0644\u064a\u0629: {0}",
                ["DocumentSerialTypeService.GetTypeByIdExceptionMessage"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u0623\u062b\u0646\u0627\u0621 \u0627\u0633\u062a\u0631\u062c\u0627\u0639 the \u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 \u0646\u0648\u0639: {0}",
                ["DocumentSerialTypeService.InternalServerError"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u062f\u0627\u062e\u0644\u064a \u0641\u064a \u0627\u0644\u062e\u0627\u062f\u0645.",
                ["DocumentSerialTypeService.TypeCreated"] = "\u0646\u0648\u0639 \u062a\u0633\u0644\u0633\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u062a\u0645 \u0625\u0646\u0634\u0627\u0624\u0647 \u0628\u0646\u062c\u0627\u062d.",
                ["DocumentSerialTypeService.TypeDeleted"] = "\u0646\u0648\u0639 \u062a\u0633\u0644\u0633\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u062a\u0645 \u062d\u0630\u0641\u0647 \u0628\u0646\u062c\u0627\u062d.",
                ["DocumentSerialTypeService.TypeNotFound"] = "\u0646\u0648\u0639 \u062a\u0633\u0644\u0633\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u063a\u064a\u0631 \u0645\u0648\u062c\u0648\u062f.",
                ["DocumentSerialTypeService.TypeRetrieved"] = "\u0646\u0648\u0639 \u062a\u0633\u0644\u0633\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u062a\u0645 \u0627\u0633\u062a\u0631\u062c\u0627\u0639\u0647 \u0628\u0646\u062c\u0627\u062d.",
                ["DocumentSerialTypeService.TypeUpdated"] = "\u0646\u0648\u0639 \u062a\u0633\u0644\u0633\u0644 \u0627\u0644\u0645\u0633\u062a\u0646\u062f \u062a\u0645 \u062a\u062d\u062f\u064a\u062b\u0647 \u0628\u0646\u062c\u0627\u062d.",
                ["DocumentSerialTypeService.TypesRetrieved"] = "\u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 Types \u062a\u0645 \u0627\u0633\u062a\u0631\u062c\u0627\u0639\u0647 \u0628\u0646\u062c\u0627\u062d.",
                ["DocumentSerialTypeService.UpdateTypeExceptionMessage"] = "\u062d\u062f\u062b \u062e\u0637\u0623 \u0623\u062b\u0646\u0627\u0621 \u062a\u062d\u062f\u064a\u062b the \u0645\u0633\u062a\u0646\u062f \u062a\u0633\u0644\u0633\u0644 \u0646\u0648\u0639: {0}",
                ["SalesTypeCreateDtoValidator.NameRequired"] = "\u0627\u0644\u0627\u0633\u0645 \u0645\u0637\u0644\u0648\u0628.",
                ["SalesTypeCreateDtoValidator.NameTooLong"] = "\u064a\u062c\u0628 \u0623\u0644\u0627 \u064a\u0632\u064a\u062f \u0627\u0644\u0627\u0633\u0645 \u0639\u0646 150 \u062d\u0631\u0641\u064b\u0627.",
                ["SalesTypeCreateDtoValidator.SalesTypeInvalid"] = "\u0646\u0648\u0639 \u0627\u0644\u0645\u0628\u064a\u0639\u0627\u062a \u063a\u064a\u0631 \u0635\u0627\u0644\u062d. \u0627\u0644\u0642\u064a\u0645 \u0627\u0644\u0645\u0633\u0645\u0648\u062d \u0628\u0647\u0627: YURTICI \u0648 YURTDISI.",
                ["SalesTypeCreateDtoValidator.SalesTypeRequired"] = "\u0646\u0648\u0639 \u0627\u0644\u0645\u0628\u064a\u0639\u0627\u062a \u0645\u0637\u0644\u0648\u0628.",
                ["SalesTypeCreateDtoValidator.SalesTypeTooLong"] = "\u064a\u062c\u0628 \u0623\u0644\u0627 \u064a\u0632\u064a\u062f \u0646\u0648\u0639 \u0627\u0644\u0645\u0628\u064a\u0639\u0627\u062a \u0639\u0646 20 \u062d\u0631\u0641\u064b\u0627.",
            },
        };
}
