using crm_api.Shared.Common.Application.Common;

namespace crm_api.Modules.Catalog.Localization;

public sealed class CatalogLocalizationResource : ILocalizationResource
{
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> MessagesByCulture { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["tr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ProductCatalogService.CatalogsRetrieved"] = "Kataloglar başarıyla getirildi.",
                ["ProductCatalogService.CatalogRetrieved"] = "Katalog başarıyla getirildi.",
                ["ProductCatalogService.CatalogCreated"] = "Katalog başarıyla oluşturuldu.",
                ["ProductCatalogService.CatalogUpdated"] = "Katalog başarıyla güncellendi.",
                ["ProductCatalogService.CatalogDeleted"] = "Katalog başarıyla silindi.",
                ["ProductCatalogService.CatalogNotFound"] = "Katalog bulunamadı.",
                ["ProductCatalogService.CatalogHasCategories"] = "Bu kataloga bağlı kategoriler olduğu için silinemez.",
                ["ProductCatalogService.CategoriesRetrieved"] = "Katalog kategorileri başarıyla getirildi.",
                ["ProductCatalogService.CategoryCreated"] = "Kategori başarıyla oluşturuldu.",
                ["ProductCatalogService.CategoryUpdated"] = "Kategori başarıyla güncellendi.",
                ["ProductCatalogService.CategoryOrderUpdated"] = "Kategori sırası başarıyla güncellendi.",
                ["ProductCatalogService.CategoryDeleted"] = "Kategori başarıyla silindi.",
                ["ProductCatalogService.CategoryNotFound"] = "Katalog kategorisi bulunamadı.",
                ["ProductCatalogService.InvalidCategoryReorderPayload"] = "Kategori sıralama verisi geçersiz.",
                ["ProductCatalogService.RulesRetrieved"] = "Kategori kuralları başarıyla getirildi.",
                ["ProductCatalogService.RuleValueOptionsRetrieved"] = "Kural değeri seçenekleri başarıyla getirildi.",
                ["ProductCatalogService.RuleCreated"] = "Kategori kuralı başarıyla oluşturuldu.",
                ["ProductCatalogService.RuleUpdated"] = "Kategori kuralı başarıyla güncellendi.",
                ["ProductCatalogService.RuleDeleted"] = "Kategori kuralı başarıyla silindi.",
                ["ProductCatalogService.RuleNotFound"] = "Kategori kuralı bulunamadı.",
                ["ProductCatalogService.RulePreviewCompleted"] = "Kural önizlemesi başarıyla hazırlandı.",
                ["ProductCatalogService.RuleApplyCompleted"] = "Kurallar başarıyla uygulandı.",
                ["ProductCatalogService.ParentCategoryNotFound"] = "Üst kategori bulunamadı.",
                ["ProductCatalogService.CategoryHasChildren"] = "Alt kategorileri olan bir kategori silinemez.",
                ["ProductCatalogService.CategoryHasStocks"] = "Bu kategoriye bağlı stoklar olduğu için silinemez.",
                ["ProductCatalogService.LeafCategoryCannotHaveChildren"] = "Alt kategorileri olan bir kayıt uç kategori olarak işaretlenemez.",
                ["ProductCatalogService.RuleNameAndValueRequired"] = "Kural adı ve kural değeri zorunludur.",
                ["ProductCatalogService.StocksRetrieved"] = "Kategoriye bağlı stoklar başarıyla getirildi.",
                ["ProductCatalogService.StockAssigned"] = "Stok kategoriye başarıyla bağlandı.",
                ["ProductCatalogService.StockAssignmentDeleted"] = "Stok bağlantısı başarıyla kaldırıldı.",
                ["ProductCatalogService.StockNotFound"] = "Stok bulunamadı.",
                ["ProductCatalogService.StockAlreadyAssigned"] = "Bu stok zaten seçili kategoriye bağlı.",
                ["ProductCatalogService.StockAssignmentNotFound"] = "Stok bağlantısı bulunamadı.",
                ["ProductCatalogService.InvalidRequest"] = "Geçersiz istek.",
                ["ProductCatalogService.NameAndCodeRequired"] = "Ad ve kod alanları zorunludur.",
                ["ProductCatalogService.CatalogCodeAlreadyExists"] = "Bu katalog kodu zaten kullanılıyor.",
                ["ProductCatalogService.CategoryCodeAlreadyExists"] = "Bu kategori kodu zaten kullanılıyor.",
                ["ProductCatalogService.InternalServerError"] = "Sunucu hatası oluştu.",
                ["ProductCatalogService.GetCatalogsExceptionMessage"] = "Kataloglar getirilirken bir hata oluştu: {0}",
                ["ProductCatalogService.GetCatalogByIdExceptionMessage"] = "Katalog detayı getirilirken bir hata oluştu: {0}",
                ["ProductCatalogService.CreateCatalogExceptionMessage"] = "Katalog oluşturulurken bir hata oluştu: {0}",
                ["ProductCatalogService.UpdateCatalogExceptionMessage"] = "Katalog güncellenirken bir hata oluştu: {0}",
                ["ProductCatalogService.DeleteCatalogExceptionMessage"] = "Katalog silinirken bir hata oluştu: {0}",
                ["ProductCatalogService.GetCatalogCategoriesExceptionMessage"] = "Katalog kategorileri getirilirken bir hata oluştu: {0}",
                ["ProductCatalogService.GetCategoryRulesExceptionMessage"] = "Kategori kuralları getirilirken bir hata oluştu: {0}",
                ["ProductCatalogService.GetCategoryRuleValueOptionsExceptionMessage"] = "Kural değeri seçenekleri getirilirken bir hata oluştu: {0}",
                ["ProductCatalogService.CreateCategoryExceptionMessage"] = "Kategori oluşturulurken bir hata oluştu: {0}",
                ["ProductCatalogService.CreateCategoryRuleExceptionMessage"] = "Kategori kuralı oluşturulurken bir hata oluştu: {0}",
                ["ProductCatalogService.UpdateCategoryExceptionMessage"] = "Kategori güncellenirken bir hata oluştu: {0}",
                ["ProductCatalogService.ReorderCategoryExceptionMessage"] = "Kategori sırası güncellenirken bir hata oluştu: {0}",
                ["ProductCatalogService.UpdateCategoryRuleExceptionMessage"] = "Kategori kuralı güncellenirken bir hata oluştu: {0}",
                ["ProductCatalogService.DeleteCategoryExceptionMessage"] = "Kategori silinirken bir hata oluştu: {0}",
                ["ProductCatalogService.DeleteCategoryRuleExceptionMessage"] = "Kategori kuralı silinirken bir hata oluştu: {0}",
                ["ProductCatalogService.PreviewCategoryRulesExceptionMessage"] = "Kategori kuralları önizlenirken bir hata oluştu: {0}",
                ["ProductCatalogService.ApplyCategoryRulesExceptionMessage"] = "Kategori kuralları uygulanırken bir hata oluştu: {0}",
                ["ProductCatalogService.CreateStockAssignmentExceptionMessage"] = "Stok bağlantısı oluşturulurken bir hata oluştu: {0}",
                ["ProductCatalogService.DeleteStockAssignmentExceptionMessage"] = "Stok bağlantısı kaldırılırken bir hata oluştu: {0}",
                ["ProductCatalogService.GetCatalogCategoryStocksExceptionMessage"] = "Kategori stokları getirilirken bir hata oluştu: {0}"
            },
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ProductCatalogService.CatalogsRetrieved"] = "Catalogs retrieved successfully.",
                ["ProductCatalogService.CatalogRetrieved"] = "Catalog retrieved successfully.",
                ["ProductCatalogService.CatalogCreated"] = "Catalog created successfully.",
                ["ProductCatalogService.CatalogUpdated"] = "Catalog updated successfully.",
                ["ProductCatalogService.CatalogDeleted"] = "Catalog deleted successfully.",
                ["ProductCatalogService.CatalogNotFound"] = "Catalog not found.",
                ["ProductCatalogService.CatalogHasCategories"] = "This catalog cannot be deleted because it has linked categories.",
                ["ProductCatalogService.CategoriesRetrieved"] = "Catalog categories retrieved successfully.",
                ["ProductCatalogService.CategoryCreated"] = "Category created successfully.",
                ["ProductCatalogService.CategoryUpdated"] = "Category updated successfully.",
                ["ProductCatalogService.CategoryOrderUpdated"] = "Category order updated successfully.",
                ["ProductCatalogService.CategoryDeleted"] = "Category deleted successfully.",
                ["ProductCatalogService.CategoryNotFound"] = "Catalog category not found.",
                ["ProductCatalogService.InvalidCategoryReorderPayload"] = "Invalid category reorder payload.",
                ["ProductCatalogService.RulesRetrieved"] = "Category rules retrieved successfully.",
                ["ProductCatalogService.RuleValueOptionsRetrieved"] = "Rule value options retrieved successfully.",
                ["ProductCatalogService.RuleCreated"] = "Category rule created successfully.",
                ["ProductCatalogService.RuleUpdated"] = "Category rule updated successfully.",
                ["ProductCatalogService.RuleDeleted"] = "Category rule deleted successfully.",
                ["ProductCatalogService.RuleNotFound"] = "Category rule not found.",
                ["ProductCatalogService.RulePreviewCompleted"] = "Rule preview generated successfully.",
                ["ProductCatalogService.RuleApplyCompleted"] = "Rules applied successfully.",
                ["ProductCatalogService.ParentCategoryNotFound"] = "Parent category not found.",
                ["ProductCatalogService.CategoryHasChildren"] = "A category with child categories cannot be deleted.",
                ["ProductCatalogService.CategoryHasStocks"] = "This category cannot be deleted because it has linked stocks.",
                ["ProductCatalogService.LeafCategoryCannotHaveChildren"] = "A category with child categories cannot be marked as leaf.",
                ["ProductCatalogService.RuleNameAndValueRequired"] = "Rule name and rule value are required.",
                ["ProductCatalogService.StocksRetrieved"] = "Category stocks retrieved successfully.",
                ["ProductCatalogService.StockAssigned"] = "Stock assigned to category successfully.",
                ["ProductCatalogService.StockAssignmentDeleted"] = "Stock assignment removed successfully.",
                ["ProductCatalogService.StockNotFound"] = "Stock not found.",
                ["ProductCatalogService.StockAlreadyAssigned"] = "This stock is already linked to the selected category.",
                ["ProductCatalogService.StockAssignmentNotFound"] = "Stock assignment not found.",
                ["ProductCatalogService.InvalidRequest"] = "Invalid request.",
                ["ProductCatalogService.NameAndCodeRequired"] = "Name and code are required.",
                ["ProductCatalogService.CatalogCodeAlreadyExists"] = "This catalog code is already in use.",
                ["ProductCatalogService.CategoryCodeAlreadyExists"] = "This category code is already in use.",
                ["ProductCatalogService.InternalServerError"] = "Internal server error occurred.",
                ["ProductCatalogService.GetCatalogsExceptionMessage"] = "An error occurred while retrieving catalogs: {0}",
                ["ProductCatalogService.GetCatalogByIdExceptionMessage"] = "An error occurred while retrieving catalog detail: {0}",
                ["ProductCatalogService.CreateCatalogExceptionMessage"] = "An error occurred while creating the catalog: {0}",
                ["ProductCatalogService.UpdateCatalogExceptionMessage"] = "An error occurred while updating the catalog: {0}",
                ["ProductCatalogService.DeleteCatalogExceptionMessage"] = "An error occurred while deleting the catalog: {0}",
                ["ProductCatalogService.GetCatalogCategoriesExceptionMessage"] = "An error occurred while retrieving catalog categories: {0}",
                ["ProductCatalogService.GetCategoryRulesExceptionMessage"] = "An error occurred while retrieving category rules: {0}",
                ["ProductCatalogService.GetCategoryRuleValueOptionsExceptionMessage"] = "An error occurred while retrieving rule value options: {0}",
                ["ProductCatalogService.CreateCategoryExceptionMessage"] = "An error occurred while creating the category: {0}",
                ["ProductCatalogService.CreateCategoryRuleExceptionMessage"] = "An error occurred while creating the category rule: {0}",
                ["ProductCatalogService.UpdateCategoryExceptionMessage"] = "An error occurred while updating the category: {0}",
                ["ProductCatalogService.ReorderCategoryExceptionMessage"] = "An error occurred while updating category order: {0}",
                ["ProductCatalogService.UpdateCategoryRuleExceptionMessage"] = "An error occurred while updating the category rule: {0}",
                ["ProductCatalogService.DeleteCategoryExceptionMessage"] = "An error occurred while deleting the category: {0}",
                ["ProductCatalogService.DeleteCategoryRuleExceptionMessage"] = "An error occurred while deleting the category rule: {0}",
                ["ProductCatalogService.PreviewCategoryRulesExceptionMessage"] = "An error occurred while previewing category rules: {0}",
                ["ProductCatalogService.ApplyCategoryRulesExceptionMessage"] = "An error occurred while applying category rules: {0}",
                ["ProductCatalogService.CreateStockAssignmentExceptionMessage"] = "An error occurred while creating the stock assignment: {0}",
                ["ProductCatalogService.DeleteStockAssignmentExceptionMessage"] = "An error occurred while deleting the stock assignment: {0}",
                ["ProductCatalogService.GetCatalogCategoryStocksExceptionMessage"] = "An error occurred while retrieving category stocks: {0}"
            }
        };
}
