using crm_api.Shared.Common.Application.Common;

namespace crm_api.Modules.PdfBuilder.Localization;

public sealed class PdfBuilderLocalizationResource : ILocalizationResource
{
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> MessagesByCulture { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Available fields retrieved successfully.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Error creating report template.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Error deleting report template.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "Error generating PDF.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Error retrieving report template.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Error retrieving report templates.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Error updating report template.",
                ["ReportTemplateService.InternalServerError"] = "Internal server error.",
                ["ReportTemplateService.InvalidTemplateData"] = "Invalid template data.",
                ["ReportTemplateService.PdfGenerated"] = "PDF generated successfully.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Report template created successfully.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Report template deleted successfully.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Report template not found.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Report template not found or inactive.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Report template retrieved successfully.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Report template updated successfully.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Report templates retrieved successfully.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "You must be signed in to generate a PDF.",
            },
            ["tr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Kullan\u0131labilir alanlar ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Rapor \u015fablonu olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Rapor \u015fablonu silinirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "PDF olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Rapor \u015fablonu getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Rapor \u015fablonlar\u0131 getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Rapor \u015fablonu g\u00fcncellenirken hata olu\u015ftu.",
                ["ReportTemplateService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["ReportTemplateService.InvalidTemplateData"] = "Ge\u00e7ersiz \u015fablon verisi.",
                ["ReportTemplateService.PdfGenerated"] = "PDF ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Rapor \u015fablonu ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Rapor \u015fablonu ba\u015far\u0131yla silindi.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Rapor \u015fablonu bulunamad\u0131.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Rapor \u015fablonu bulunamad\u0131 veya pasif.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Rapor \u015fablonu ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Rapor \u015fablonu ba\u015far\u0131yla g\u00fcncellendi.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Rapor \u015fablonlar\u0131 ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "PDF olu\u015fturmak i\u00e7in giri\u015f yapmal\u0131s\u0131n\u0131z.",
            },
            ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Kullan\u0131labilir alanlar ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Rapor \u015fablonu olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Rapor \u015fablonu silinirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "PDF olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Rapor \u015fablonu getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Rapor \u015fablonlar\u0131 getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Rapor \u015fablonu g\u00fcncellenirken hata olu\u015ftu.",
                ["ReportTemplateService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["ReportTemplateService.InvalidTemplateData"] = "Ge\u00e7ersiz \u015fablon verisi.",
                ["ReportTemplateService.PdfGenerated"] = "PDF ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Rapor \u015fablonu ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Rapor \u015fablonu ba\u015far\u0131yla silindi.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Rapor \u015fablonu bulunamad\u0131.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Rapor \u015fablonu bulunamad\u0131 veya pasif.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Rapor \u015fablonu ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Rapor \u015fablonu ba\u015far\u0131yla g\u00fcncellendi.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Rapor \u015fablonlar\u0131 ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "Datensatz erfolgreich abgerufen.",
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Kullan\u0131labilir alanlar ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Rapor \u015fablonu olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Rapor \u015fablonu silinirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "PDF olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Rapor \u015fablonu getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Rapor \u015fablonlar\u0131 getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Rapor \u015fablonu g\u00fcncellenirken hata olu\u015ftu.",
                ["ReportTemplateService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["ReportTemplateService.InvalidTemplateData"] = "Ge\u00e7ersiz \u015fablon verisi.",
                ["ReportTemplateService.PdfGenerated"] = "PDF ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Rapor \u015fablonu ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Rapor \u015fablonu ba\u015far\u0131yla silindi.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Rapor \u015fablonu bulunamad\u0131.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Rapor \u015fablonu bulunamad\u0131 veya pasif.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Rapor \u015fablonu ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Rapor \u015fablonu ba\u015far\u0131yla g\u00fcncellendi.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Rapor \u015fablonlar\u0131 ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "Enregistrement r\u00e9cup\u00e9r\u00e9 avec succ\u00e8s.",
            },
            ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Kullan\u0131labilir alanlar ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Rapor \u015fablonu olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Rapor \u015fablonu silinirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "PDF olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Rapor \u015fablonu getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Rapor \u015fablonlar\u0131 getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Rapor \u015fablonu g\u00fcncellenirken hata olu\u015ftu.",
                ["ReportTemplateService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["ReportTemplateService.InvalidTemplateData"] = "Ge\u00e7ersiz \u015fablon verisi.",
                ["ReportTemplateService.PdfGenerated"] = "PDF ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Rapor \u015fablonu ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Rapor \u015fablonu ba\u015far\u0131yla silindi.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Rapor \u015fablonu bulunamad\u0131.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Rapor \u015fablonu bulunamad\u0131 veya pasif.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Rapor \u015fablonu ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Rapor \u015fablonu ba\u015far\u0131yla g\u00fcncellendi.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Rapor \u015fablonlar\u0131 ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "Registro recuperado correctamente.",
            },
            ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Kullan\u0131labilir alanlar ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Rapor \u015fablonu olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Rapor \u015fablonu silinirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "PDF olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Rapor \u015fablonu getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Rapor \u015fablonlar\u0131 getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Rapor \u015fablonu g\u00fcncellenirken hata olu\u015ftu.",
                ["ReportTemplateService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["ReportTemplateService.InvalidTemplateData"] = "Ge\u00e7ersiz \u015fablon verisi.",
                ["ReportTemplateService.PdfGenerated"] = "PDF ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Rapor \u015fablonu ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Rapor \u015fablonu ba\u015far\u0131yla silindi.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Rapor \u015fablonu bulunamad\u0131.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Rapor \u015fablonu bulunamad\u0131 veya pasif.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Rapor \u015fablonu ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Rapor \u015fablonu ba\u015far\u0131yla g\u00fcncellendi.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Rapor \u015fablonlar\u0131 ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "Record recuperato con successo.",
            },
            ["ar"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["ReportTemplateController.AvailableFieldsRetrieved"] = "Kullan\u0131labilir alanlar ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ErrorCreatingReportTemplate"] = "Rapor \u015fablonu olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorDeletingReportTemplate"] = "Rapor \u015fablonu silinirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorGeneratingPdf"] = "PDF olu\u015fturulurken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplate"] = "Rapor \u015fablonu getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorRetrievingReportTemplates"] = "Rapor \u015fablonlar\u0131 getirilirken hata olu\u015ftu.",
                ["ReportTemplateService.ErrorUpdatingReportTemplate"] = "Rapor \u015fablonu g\u00fcncellenirken hata olu\u015ftu.",
                ["ReportTemplateService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["ReportTemplateService.InvalidTemplateData"] = "Ge\u00e7ersiz \u015fablon verisi.",
                ["ReportTemplateService.PdfGenerated"] = "PDF ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateCreated"] = "Rapor \u015fablonu ba\u015far\u0131yla olu\u015fturuldu.",
                ["ReportTemplateService.ReportTemplateDeleted"] = "Rapor \u015fablonu ba\u015far\u0131yla silindi.",
                ["ReportTemplateService.ReportTemplateNotFound"] = "Rapor \u015fablonu bulunamad\u0131.",
                ["ReportTemplateService.ReportTemplateNotFoundOrInactive"] = "Rapor \u015fablonu bulunamad\u0131 veya pasif.",
                ["ReportTemplateService.ReportTemplateRetrieved"] = "Rapor \u015fablonu ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.ReportTemplateUpdated"] = "Rapor \u015fablonu ba\u015far\u0131yla g\u00fcncellendi.",
                ["ReportTemplateService.ReportTemplatesRetrieved"] = "Rapor \u015fablonlar\u0131 ba\u015far\u0131yla getirildi.",
                ["ReportTemplateService.UnauthorizedGenerate"] = "\u062a\u0645 \u062c\u0644\u0628 \u0627\u0644\u0633\u062c\u0644 \u0628\u0646\u062c\u0627\u062d.",
            },
        };
}
