using crm_api.Shared.Common.Application.Common;

namespace crm_api.Modules.Notification.Localization;

public sealed class NotificationLocalizationResource : ILocalizationResource
{
    public IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> MessagesByCulture { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "Demand {0} is pending approval.",
                ["Notification.DemandApproval.Title"] = "Demand Pending Approval",
                ["Notification.DemandApproved.Message"] = "Demand {0} has been approved.",
                ["Notification.DemandApproved.Title"] = "Demand Approved",
                ["Notification.OrderApproval.Message"] = "Order {0} is pending approval.",
                ["Notification.OrderApproval.Title"] = "Order Pending Approval",
                ["Notification.OrderApproved.Message"] = "Order {0} has been approved.",
                ["Notification.OrderApproved.Title"] = "Order Approved",
                ["Notification.QuotationApproval.Message"] = "Quotation {0} is pending approval.",
                ["Notification.QuotationApproval.Title"] = "Quotation Pending Approval",
                ["Notification.QuotationApproved.Message"] = "Quotation {0} has been approved.",
                ["Notification.QuotationApproved.Title"] = "Quotation Approved",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "All notifications marked as read.",
                ["NotificationService.InternalServerError"] = "Internal server error.",
                ["NotificationService.NotificationCreated"] = "Notification created.",
                ["NotificationService.NotificationDeleted"] = "Notification deleted.",
                ["NotificationService.NotificationMarkedAsRead"] = "Notification marked as read.",
                ["NotificationService.NotificationNotFound"] = "Notification not found.",
                ["NotificationService.NotificationsRetrieved"] = "Notifications retrieved successfully.",
                ["NotificationService.UnreadCountRetrieved"] = "Unread count retrieved.",
            },
            ["tr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "{0} numaral\u0131 talep onay beklemektedir.",
                ["Notification.DemandApproval.Title"] = "Onay Bekleyen Talep",
                ["Notification.DemandApproved.Message"] = "{0} numaral\u0131 talep onayland\u0131.",
                ["Notification.DemandApproved.Title"] = "Talep Onayland\u0131",
                ["Notification.OrderApproval.Message"] = "{0} numaral\u0131 sipari\u015f onay beklemektedir.",
                ["Notification.OrderApproval.Title"] = "Onay Bekleyen Sipari\u015f",
                ["Notification.OrderApproved.Message"] = "{0} numaral\u0131 sipari\u015f onayland\u0131.",
                ["Notification.OrderApproved.Title"] = "Sipari\u015f Onayland\u0131",
                ["Notification.QuotationApproval.Message"] = "{0} numaral\u0131 teklif onay beklemektedir.",
                ["Notification.QuotationApproval.Title"] = "Onay Bekleyen Teklif",
                ["Notification.QuotationApproved.Message"] = "{0} numaral\u0131 teklif onayland\u0131.",
                ["Notification.QuotationApproved.Title"] = "Teklif Onayland\u0131",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "T\u00fcm bildirimler okundu olarak i\u015faretlendi.",
                ["NotificationService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["NotificationService.NotificationCreated"] = "Bildirim olu\u015fturuldu.",
                ["NotificationService.NotificationDeleted"] = "Bildirim silindi.",
                ["NotificationService.NotificationMarkedAsRead"] = "Bildirim okundu olarak i\u015faretlendi.",
                ["NotificationService.NotificationNotFound"] = "Bildirim bulunamad\u0131.",
                ["NotificationService.NotificationsRetrieved"] = "Bildirimler ba\u015far\u0131yla getirildi.",
                ["NotificationService.UnreadCountRetrieved"] = "Okunmam\u0131\u015f bildirim say\u0131s\u0131 getirildi.",
            },
            ["de"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "{0} numaral\u0131 talep onay beklemektedir.",
                ["Notification.DemandApproval.Title"] = "Onay Bekleyen Talep",
                ["Notification.DemandApproved.Message"] = "{0} numaral\u0131 talep onayland\u0131.",
                ["Notification.DemandApproved.Title"] = "Talep Onayland\u0131",
                ["Notification.OrderApproval.Message"] = "{0} numaral\u0131 sipari\u015f onay beklemektedir.",
                ["Notification.OrderApproval.Title"] = "Onay Bekleyen Sipari\u015f",
                ["Notification.OrderApproved.Message"] = "{0} numaral\u0131 sipari\u015f onayland\u0131.",
                ["Notification.OrderApproved.Title"] = "Sipari\u015f Onayland\u0131",
                ["Notification.QuotationApproval.Message"] = "{0} numaral\u0131 teklif onay beklemektedir.",
                ["Notification.QuotationApproval.Title"] = "Onay Bekleyen Teklif",
                ["Notification.QuotationApproved.Message"] = "{0} numaral\u0131 teklif onayland\u0131.",
                ["Notification.QuotationApproved.Title"] = "Teklif Onayland\u0131",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "T\u00fcm bildirimler okundu olarak i\u015faretlendi.",
                ["NotificationService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["NotificationService.NotificationCreated"] = "Bildirim olu\u015fturuldu.",
                ["NotificationService.NotificationDeleted"] = "Bildirim silindi.",
                ["NotificationService.NotificationMarkedAsRead"] = "Bildirim okundu olarak i\u015faretlendi.",
                ["NotificationService.NotificationNotFound"] = "Bildirim bulunamad\u0131.",
                ["NotificationService.NotificationsRetrieved"] = "Bildirimler ba\u015far\u0131yla getirildi.",
                ["NotificationService.UnreadCountRetrieved"] = "Okunmam\u0131\u015f bildirim say\u0131s\u0131 getirildi.",
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "{0} numaral\u0131 talep onay beklemektedir.",
                ["Notification.DemandApproval.Title"] = "Onay Bekleyen Talep",
                ["Notification.DemandApproved.Message"] = "{0} numaral\u0131 talep onayland\u0131.",
                ["Notification.DemandApproved.Title"] = "Talep Onayland\u0131",
                ["Notification.OrderApproval.Message"] = "{0} numaral\u0131 sipari\u015f onay beklemektedir.",
                ["Notification.OrderApproval.Title"] = "Onay Bekleyen Sipari\u015f",
                ["Notification.OrderApproved.Message"] = "{0} numaral\u0131 sipari\u015f onayland\u0131.",
                ["Notification.OrderApproved.Title"] = "Sipari\u015f Onayland\u0131",
                ["Notification.QuotationApproval.Message"] = "{0} numaral\u0131 teklif onay beklemektedir.",
                ["Notification.QuotationApproval.Title"] = "Onay Bekleyen Teklif",
                ["Notification.QuotationApproved.Message"] = "{0} numaral\u0131 teklif onayland\u0131.",
                ["Notification.QuotationApproved.Title"] = "Teklif Onayland\u0131",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "T\u00fcm bildirimler okundu olarak i\u015faretlendi.",
                ["NotificationService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["NotificationService.NotificationCreated"] = "Bildirim olu\u015fturuldu.",
                ["NotificationService.NotificationDeleted"] = "Bildirim silindi.",
                ["NotificationService.NotificationMarkedAsRead"] = "Bildirim okundu olarak i\u015faretlendi.",
                ["NotificationService.NotificationNotFound"] = "Bildirim bulunamad\u0131.",
                ["NotificationService.NotificationsRetrieved"] = "Bildirimler ba\u015far\u0131yla getirildi.",
                ["NotificationService.UnreadCountRetrieved"] = "Okunmam\u0131\u015f bildirim say\u0131s\u0131 getirildi.",
            },
            ["es"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "{0} numaral\u0131 talep onay beklemektedir.",
                ["Notification.DemandApproval.Title"] = "Onay Bekleyen Talep",
                ["Notification.DemandApproved.Message"] = "{0} numaral\u0131 talep onayland\u0131.",
                ["Notification.DemandApproved.Title"] = "Talep Onayland\u0131",
                ["Notification.OrderApproval.Message"] = "{0} numaral\u0131 sipari\u015f onay beklemektedir.",
                ["Notification.OrderApproval.Title"] = "Onay Bekleyen Sipari\u015f",
                ["Notification.OrderApproved.Message"] = "{0} numaral\u0131 sipari\u015f onayland\u0131.",
                ["Notification.OrderApproved.Title"] = "Sipari\u015f Onayland\u0131",
                ["Notification.QuotationApproval.Message"] = "{0} numaral\u0131 teklif onay beklemektedir.",
                ["Notification.QuotationApproval.Title"] = "Onay Bekleyen Teklif",
                ["Notification.QuotationApproved.Message"] = "{0} numaral\u0131 teklif onayland\u0131.",
                ["Notification.QuotationApproved.Title"] = "Teklif Onayland\u0131",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "T\u00fcm bildirimler okundu olarak i\u015faretlendi.",
                ["NotificationService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["NotificationService.NotificationCreated"] = "Bildirim olu\u015fturuldu.",
                ["NotificationService.NotificationDeleted"] = "Bildirim silindi.",
                ["NotificationService.NotificationMarkedAsRead"] = "Bildirim okundu olarak i\u015faretlendi.",
                ["NotificationService.NotificationNotFound"] = "Bildirim bulunamad\u0131.",
                ["NotificationService.NotificationsRetrieved"] = "Bildirimler ba\u015far\u0131yla getirildi.",
                ["NotificationService.UnreadCountRetrieved"] = "Okunmam\u0131\u015f bildirim say\u0131s\u0131 getirildi.",
            },
            ["it"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "{0} numaral\u0131 talep onay beklemektedir.",
                ["Notification.DemandApproval.Title"] = "Onay Bekleyen Talep",
                ["Notification.DemandApproved.Message"] = "{0} numaral\u0131 talep onayland\u0131.",
                ["Notification.DemandApproved.Title"] = "Talep Onayland\u0131",
                ["Notification.OrderApproval.Message"] = "{0} numaral\u0131 sipari\u015f onay beklemektedir.",
                ["Notification.OrderApproval.Title"] = "Onay Bekleyen Sipari\u015f",
                ["Notification.OrderApproved.Message"] = "{0} numaral\u0131 sipari\u015f onayland\u0131.",
                ["Notification.OrderApproved.Title"] = "Sipari\u015f Onayland\u0131",
                ["Notification.QuotationApproval.Message"] = "{0} numaral\u0131 teklif onay beklemektedir.",
                ["Notification.QuotationApproval.Title"] = "Onay Bekleyen Teklif",
                ["Notification.QuotationApproved.Message"] = "{0} numaral\u0131 teklif onayland\u0131.",
                ["Notification.QuotationApproved.Title"] = "Teklif Onayland\u0131",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "T\u00fcm bildirimler okundu olarak i\u015faretlendi.",
                ["NotificationService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["NotificationService.NotificationCreated"] = "Bildirim olu\u015fturuldu.",
                ["NotificationService.NotificationDeleted"] = "Bildirim silindi.",
                ["NotificationService.NotificationMarkedAsRead"] = "Bildirim okundu olarak i\u015faretlendi.",
                ["NotificationService.NotificationNotFound"] = "Bildirim bulunamad\u0131.",
                ["NotificationService.NotificationsRetrieved"] = "Bildirimler ba\u015far\u0131yla getirildi.",
                ["NotificationService.UnreadCountRetrieved"] = "Okunmam\u0131\u015f bildirim say\u0131s\u0131 getirildi.",
            },
            ["ar"] = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                ["Notification.DemandApproval.Message"] = "{0} numaral\u0131 talep onay beklemektedir.",
                ["Notification.DemandApproval.Title"] = "Onay Bekleyen Talep",
                ["Notification.DemandApproved.Message"] = "{0} numaral\u0131 talep onayland\u0131.",
                ["Notification.DemandApproved.Title"] = "Talep Onayland\u0131",
                ["Notification.OrderApproval.Message"] = "{0} numaral\u0131 sipari\u015f onay beklemektedir.",
                ["Notification.OrderApproval.Title"] = "Onay Bekleyen Sipari\u015f",
                ["Notification.OrderApproved.Message"] = "{0} numaral\u0131 sipari\u015f onayland\u0131.",
                ["Notification.OrderApproved.Title"] = "Sipari\u015f Onayland\u0131",
                ["Notification.QuotationApproval.Message"] = "{0} numaral\u0131 teklif onay beklemektedir.",
                ["Notification.QuotationApproval.Title"] = "Onay Bekleyen Teklif",
                ["Notification.QuotationApproved.Message"] = "{0} numaral\u0131 teklif onayland\u0131.",
                ["Notification.QuotationApproved.Title"] = "Teklif Onayland\u0131",
                ["NotificationService.AllNotificationsMarkedAsRead"] = "T\u00fcm bildirimler okundu olarak i\u015faretlendi.",
                ["NotificationService.InternalServerError"] = "Dahili sunucu hatas\u0131 olu\u015ftu.",
                ["NotificationService.NotificationCreated"] = "Bildirim olu\u015fturuldu.",
                ["NotificationService.NotificationDeleted"] = "Bildirim silindi.",
                ["NotificationService.NotificationMarkedAsRead"] = "Bildirim okundu olarak i\u015faretlendi.",
                ["NotificationService.NotificationNotFound"] = "Bildirim bulunamad\u0131.",
                ["NotificationService.NotificationsRetrieved"] = "Bildirimler ba\u015far\u0131yla getirildi.",
                ["NotificationService.UnreadCountRetrieved"] = "Okunmam\u0131\u015f bildirim say\u0131s\u0131 getirildi.",
            },
        };
}
